[package]
name = "foot-card-game-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.134"

[dependencies.serde]
version = "1.0.217"
features = [
    "derive",
]

[dependencies.uuid]
version = "1.11.0"
features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
]
